---
title: Tiny Kite
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  portfolio:
    title: Portfolio
    output: true
    permalink: "/portfolio/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      section: "Portfolio"
  -
    scope:
      path: ""
      type: "posts"
    values:
      section: "Writing"

email: dakota@tinykitelab.com
description: Tiny Kite is the interdisciplinary design practice of Dakota Sexton,
  a fierce bird with an appetite for code and creative storytelling.
baseurl: ''
url: ''
markdown: kramdown
plugins:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
